export type Lang = "ar" | "en";

export const productSlugs = [
  "ferro-alloys",
  "carbourisers",
  "virgin-metals",
  "minerals-ores",
  "refractories",
  "steel-products",
  "cements",
] as const;

export type ProductSlug = (typeof productSlugs)[number];

export const content = {
  ar: {
    dir: "rtl" as const,
    brand: "توب تراست للمنتجات المعدنية",
    brandShort: "توب تراست",
    tagline: "مبني على الثقة",
    nav: {
      home: "الرئيسية",
      products: "المنتجات",
      services: "الخدمات",
      about: "من نحن",
      contact: "تواصل معنا",
    },
    common: {
      viewDetails: "تفاصيل الفئة",
      backToProducts: "العودة للمنتجات",
      specs: "معلومات التوريد",
      uses: "مجالات الاستخدام",
      relatedProducts: "فئات أخرى",
      viewAll: "عرض الكل",
      requestProduct: "اطلب عرض سعر لهذه الفئة",
    },
    hero: {
      eyebrow: "شركة توب تراست للاستيراد والتصدير · خامات ومواد صناعية",
      title: "مواد معدنية",
      titleAccent: "لإنتاج يعتمد عليه",
      body: "شركة متخصصة في استيراد وتصدير السبائك الحديدية، مواد الكربنة، المعادن النقية، الخامات، المواد الحرارية والمستلزمات المرتبطة بصناعات الحديد والصلب والمسابك.",
      cta: "اطلب عرض سعر",
      cta2: "تصفح المنتجات",
    },
    seo: {
      title: "توب تراست للمنتجات المعدنية | خامات ومواد صناعية",
      description:
        "توب تراست للاستيراد والتصدير: سبائك حديدية، مواد كربنة، معادن نقية، خامات، مواد حرارية ومنتجات الصلب.",
    },
    stats: [
      { value: "7", label: "فئات منتجات" },
      { value: "50+", label: "منتج ومادة صناعية" },
      { value: "B2B", label: "توريد للشركات" },
      { value: "دولي", label: "استيراد وتصدير" },
    ],
    productsSection: {
      eyebrow: "المنتجات",
      title: "محفظة متكاملة لصناعات الحديد والصلب والمسابك",
      body: "اكتشف فئاتنا الرئيسية من السبائك الحديدية ومواد الكربنة إلى المعادن النقية والخامات والمواد الحرارية والأسمنت.",
      note: "تتوفر الخامات والمنتجات بمواصفات وكميات صناعية حسب متطلبات العميل، مع إمكانية مشاركة شهادات التحليل عند الطلب.",
    },
    products: [
      {
        slug: "ferro-alloys",
        name: "FERRO ALLOYS",
        categoryEn: "Ferro Alloys",
         spec: "20 alloy and treatment products",
         desc: "مجموعة واسعة من السبائك الحديدية ومواد المعالجة لصناعة الصلب والمسابك وإنتاج السبائك.",
         long: "نوفر السبائك الحديدية ومواد المعالجة المستخدمة لضبط التركيب الكيميائي وتحسين الخواص المطلوبة في إنتاج الصلب والمسبوكات. يمكن تحديد الدرجات والأحجام وفقاً لمتطلبات العملية والمواصفة المطلوبة.",
        items: [
          "Ferro Silicon",
          "High Carbon Ferro Manganese",
          "Medium Carbon Ferro Manganese",
          "Low Carbon Ferro Manganese",
          "High Carbon Ferro Chrome",
          "Low Carbon Ferro Chrome",
          "High Carbon Silicon Manganese",
          "Medium Carbon Silicon Manganese",
          "Low Carbon Silicon Manganese",
          "Ferro Silicon Calcium",
          "Ferro Molybdenum",
          "Ferro Vanadium",
          "Ferro Silicon Magnesium",
          "Ferro Boron",
          "Ferro Titanium",
          "Ferro Phosphorous",
          "Ferro Niobium",
          "Calcium Carbide",
          "Ferro Sulphur",
          "Ferro Silicon Barium",
        ],
        specs: [
          { k: "Category", v: "Ferro alloys and metallurgical additives" },
          { k: "Applications", v: "Steelmaking, foundries and alloy production" },
          { k: "Supply", v: "Industrial quantities and agreed grades" },
          { k: "Documentation", v: "Analysis certificates available on request" },
        ],
        uses: ["Steelmaking", "Foundries", "Special alloy production", "Metal treatment"],
      },
      {
        slug: "carbourisers",
        name: "CARBURISERS",
        categoryEn: "Carburisers",
         spec: "6 carbon additive products",
        desc: "مواد كربنة ورفع للكربون لصناعة الصلب والمسابك.",
        long: "تساعد مواد رفع الكربون على التحكم في نسبة الكربون والحفاظ على ثبات التركيب الكيميائي للمصهور. نوفر فحم البترول وفحم الميتكوك ومواد الكربنة بدرجات كبريت مختلفة.",
        items: [
          "Graphitized Petroleum Coke",
          "Petroleum Coke",
          "Metcoke",
          "High & Low Sulphur Carburiser",
          "Steam Coke",
          "Anthracite",
        ],
        specs: [
          { k: "Category", v: "Carbon raisers and carburising materials" },
          { k: "Applications", v: "Foundry, induction furnace and steelmaking" },
          { k: "Options", v: "High and low sulphur grades" },
          { k: "Supply", v: "Bulk and bagged supply by agreement" },
        ],
        uses: ["Iron foundries", "Steel foundries", "Induction furnaces", "Melt chemistry control"],
      },
      {
        slug: "virgin-metals",
        name: "VIRGIN METALS",
        categoryEn: "Virgin Metals",
        spec: "5 primary metal products",
        desc: "معادن أولية للخلط والصهر والتحكم في التركيب الكيميائي الصناعي.",
        long: "توفر مجموعة المعادن النقية مواد أولية مناسبة لإضافات المسابك وإنتاج السبائك وعمليات الصهر الصناعية. يمكن تحديد الدرجة والشكل والتعبئة وجدول التسليم حسب كل طلب.",
        items: ["Silicon Metal", "Manganese Metal", "Magnesium Metal", "Moly Metal", "Zinc"],
        specs: [
          { k: "Category", v: "Primary and virgin metals" },
          { k: "Applications", v: "Alloying, melting and metal production" },
          { k: "Supply", v: "Grade, form and packing by requirement" },
          { k: "Documentation", v: "Product documentation available on request" },
        ],
        uses: ["Alloy production", "Foundry additions", "Metal refining", "Industrial melting"],
      },
      {
        slug: "minerals-ores",
        name: "MINERALS & ORES",
        categoryEn: "Minerals & Ores",
        spec: "7 mineral and ore products",
        desc: "معادن وخامات صناعية ومواد تغذية للأفران لعمليات المعالجة.",
        long: "نوفر مجموعة مختارة من المعادن والخامات للمعالجة الصناعية وتحضير المواد الحرارية وعمليات الأفران. يتم تأكيد التوافر والمقاسات ومعايير الجودة لكل طلب.",
        items: [
          "Iron Ore",
          "Bauxite",
          "Magnesium Ore",
          "Iron Ore Pellet",
          "Calcine",
          "Silica Sand",
          "Manganese Ore",
        ],
        specs: [
          { k: "Category", v: "Minerals, ores and processed feed materials" },
          { k: "Applications", v: "Steel, foundry, refractory and industrial processing" },
          { k: "Supply", v: "Bulk, container and agreed packing options" },
          { k: "Quality", v: "Parameters confirmed against the enquiry" },
        ],
        uses: ["Steel production", "Furnace feed", "Refractory production", "Industrial processing"],
      },
      {
        slug: "refractories",
        name: "REFRACTORIES",
        categoryEn: "Refractories",
        spec: "5 refractory products",
        desc: "خلطات دك وأسمنت حراري وطين ناري لتبطين الأفران.",
        long: "يتم اختيار المواد الحرارية لدينا لتبطين الأفران والإصلاحات والتطبيقات المقاومة للحرارة. نوفر خلطات الدك الحمضية والقاعدية والأسمنت الحراري والطين الناري للصيانة والتركيبات الجديدة.",
        items: ["Acidic Ramming Mass", "Basic Ramming Mass", "Castable Cements", "Fire Clay", "Boric Acid"],
        specs: [
          { k: "Category", v: "Furnace and heat-resistant materials" },
          { k: "Applications", v: "Lining, repair and maintenance" },
          { k: "Products", v: "Ramming masses, castables and fire clay" },
          { k: "Supply", v: "Industrial quantities and agreed packing" },
        ],
        uses: ["Induction furnaces", "Furnace lining", "Hot repair", "Foundry maintenance"],
      },
      {
        slug: "steel-products",
        name: "منتجات الصلب",
        categoryEn: "Steel Products",
        spec: "6 steel products",
        desc: "منتجات الصلب والخردة لتلبية احتياجات المصانع والمشروعات الصناعية.",
        long: "نوفر منتجات الصلب والخردة لمصانع الحديد والصلب والمشروعات الصناعية، مع تنسيق المواصفات والكميات والتعبئة حسب متطلبات العميل.",
        items: [
          "حديد تسليح",
          "لفة سلك",
          "بليت",
          "خردة حديد",
          "خردة معادن غير حديدية",
          "نص مصنع",
        ],
        specs: [
          { k: "الفئة", v: "منتجات الصلب والخردة" },
          { k: "الاستخدامات", v: "المشروعات الإنشائية ومصانع الحديد والصلب" },
          { k: "التوريد", v: "كميات ومواصفات صناعية حسب الطلب" },
          { k: "التعبئة", v: "تُحدد وفقاً لطبيعة المنتج والشحنة" },
        ],
        uses: ["مشروعات الإنشاء", "مصانع الحديد والصلب", "التصنيع الصناعي", "إعادة التدوير"],
      },
      {
        slug: "cements",
        name: "الأسمنت",
        categoryEn: "Cements",
        spec: "10 cement products",
        subheading: "أنواع الأسمنت",
        subdescription: "نوفر توريد مختلف أنواع الأسمنت",
        desc: "وكلاء وممثلون لكبرى مصانع الأسمنت في مصر",
        long: "وكلاء وممثلون معتمدون لعدد من كبرى مصانع الأسمنت في مصر، ونوفر مجموعة متكاملة من أنواع الأسمنت والخامات والمواد المستخدمة في صناعة الأسمنت، مع حلول توريد موثوقة تلبي احتياجات شركات المقاولات والمصانع والمشروعات الصناعية والإنشائية.",
        items: [
          "الأسمنت البورتلاندي العادي OPC",
          "الأسمنت البورتلاندي المقاوم للكبريتات SRC",
          "الأسمنت البورتلاندي المركب CEM II / A-M",
          "الأسمنت البورتلاندي المركب CEM II / B-M",
          "الأسمنت البوزولاني CEM IV",
          "الأسمنت الخبثي CEM III",
          "الأسمنت الأبيض",
          "أسمنت التشطيبات",
          "أسمنت آبار البترول G",
          "خامات الأسمنت: حجر جيري، طفلة، جبس، رمل سيليكا",
        ],
        specs: [
          { k: "الفئة", v: "أسمنت وخامات صناعة الأسمنت" },
          { k: "التوريد", v: "توريد مباشر من مصانع معتمدة حسب الطلب" },
          { k: "الاستخدامات", v: "المقاولات والمصانع والمشروعات الإنشائية" },
          { k: "التوثيق", v: "المواصفات وشهادات التحليل عند الطلب" },
        ],
        uses: ["المقاولات", "المشروعات الصناعية", "المشروعات الإنشائية", "مصانع الأسمنت"],
      },
    ],
    servicesSection: {
      eyebrow: "الخدمات",
      title: "من اختيار المادة إلى التسليم",
      body: "نساعدك في تحديد المنتج المناسب، تنسيق التوريد، وتجهيز الشحنة لمتطلبات عملك.",
    },
    services: [
      {
        n: "01",
        t: "تحديد المنتج",
        d: "مراجعة متطلبات العميل وربطها بالفئة والدرجة والمواصفة المناسبة.",
      },
      { n: "02", t: "التوريد والاستيراد", d: "تنسيق مصادر التوريد والشحن للمنتجات المعدنية والخامات." },
      { n: "03", t: "المواصفات والتحليل", d: "مشاركة بيانات المنتج وشهادات التحليل عند توفرها وطلبها." },
      { n: "04", t: "التعبئة والتجهيز", d: "ترتيب التعبئة والكميات بما يناسب التخزين والنقل والاستخدام." },
      { n: "05", t: "التصدير", d: "تنسيق المستندات والشحنات لعملاء الاستيراد والتصدير." },
      { n: "06", t: "المتابعة التجارية", d: "استجابة مباشرة للطلبات والاستفسارات وعروض الأسعار." },
    ],
    about: {
      eyebrow: "من نحن",
      title: "شريك توريد لصناعات المعادن والمسابك",
      body: "تعمل شركة توب تراست للاستيراد والتصدير على توفير مواد معدنية وخامات صناعية لعملاء الحديد والصلب والمسابك والتصنيع. نركز على وضوح المواصفات، مرونة التوريد، وسرعة التواصل من أول استفسار حتى إتمام الشحنة.",
      points: [
        "سبائك حديدية ومضافات ميتالورجية",
        "مواد كربنة ونودولايزر وإنوكولانت",
        "معادن نقية وخامات ومواد حرارية",
        "توريد واستيراد وتصدير حسب متطلبات العميل",
      ],
    },
    contact: {
      eyebrow: "تواصل",
      title: "اطلب عرض سعر",
      body: "أرسل اسم المنتج والكمية والمواصفة المطلوبة، وسنعود إليك بتفاصيل التوريد.",
      name: "الاسم",
      company: "الجهة / الشركة",
      emailLabel: "البريد الإلكتروني",
      message: "تفاصيل الطلب",
      submit: "إرسال الطلب",
      sent: "تم استلام طلبك، سنعاود التواصل قريباً.",
      sending: "جاري الإرسال...",
      sendError: "تعذر إرسال الطلب. يرجى المحاولة مرة أخرى أو التواصل معنا مباشرة.",
      emailSetup: "لم يتم إعداد خدمة البريد الإلكتروني بعد.",
      phoneLabel: "الهاتف",
      mailLabel: "البريد",
      addressLabel: "العنوان",
      address: "شركة توب تراست للاستيراد والتصدير",
      phone: "+20 104 444 9783",
      email: "info@toptrustco.com",
      emailSecondary: "ahmed@toptrustco.com",
    },
    footerNote: "جميع الحقوق محفوظة",
    langToggle: "EN",
  },
  en: {
    dir: "ltr" as const,
    brand: "Top Trust Metal Products",
    brandShort: "Top Trust",
    tagline: "Built on trust",
    nav: {
      home: "Home",
      products: "Products",
      services: "Services",
      about: "About",
      contact: "Contact",
    },
    common: {
      viewDetails: "View category",
      backToProducts: "Back to products",
      specs: "Supply information",
      uses: "Applications",
      relatedProducts: "Other categories",
      viewAll: "View all",
      requestProduct: "Request a quote for this category",
    },
    hero: {
      eyebrow: "Top Trust · Industrial materials import and export",
      title: "Metal materials",
      titleAccent: "for dependable production",
      body: "A specialist importer and exporter of ferro alloys, carburisers, virgin metals, minerals and ores, refractories, and related materials for steelmaking, foundries and industrial operations.",
      cta: "Request a quote",
      cta2: "Browse products",
    },
    seo: {
      title: "Top Trust Metal Products | Industrial Materials",
      description:
        "Top Trust imports and exports ferro alloys, carburisers, virgin metals, minerals, ores, refractories, steel products and cement.",
    },
    stats: [
      { value: "7", label: "Product categories" },
      { value: "50+", label: "Industrial products" },
      { value: "B2B", label: "Business supply" },
      { value: "Global", label: "Import & export" },
    ],
    productsSection: {
      eyebrow: "Products",
      title: "A complete range for steel, foundry and industrial production",
      body: "Explore our main categories, from ferro alloys and carbon additives to virgin metals, minerals, ores, refractories, steel products and cement.",
      note: "Products are available in industrial quantities and agreed specifications, with analysis documentation available on request.",
    },
    products: [
      {
        slug: "ferro-alloys",
        name: "FERRO ALLOYS",
        categoryEn: "Ferro Alloys",
        spec: "20 alloy and treatment products",
        desc: "A broad range of ferro alloys and treatment materials for steelmaking, foundries and alloy production.",
        long: "We supply ferro alloys and treatment materials used to adjust chemistry, improve performance and achieve the required metallurgical properties in steel and foundry production. Grades and sizing can be discussed according to the customer’s process and specification.",
        items: [
          "Ferro Silicon",
          "High Carbon Ferro Manganese",
          "Medium Carbon Ferro Manganese",
          "Low Carbon Ferro Manganese",
          "High Carbon Ferro Chrome",
          "Low Carbon Ferro Chrome",
          "High Carbon Silicon Manganese",
          "Medium Carbon Silicon Manganese",
          "Low Carbon Silicon Manganese",
          "Ferro Silicon Calcium",
          "Ferro Molybdenum",
          "Ferro Vanadium",
          "Ferro Silicon Magnesium",
          "Ferro Boron",
          "Ferro Titanium",
          "Ferro Phosphorous",
          "Ferro Niobium",
          "Calcium Carbide",
          "Ferro Sulphur",
          "Ferro Silicon Barium",
        ],
        specs: [
          { k: "Category", v: "Ferro alloys and metallurgical additives" },
          { k: "Applications", v: "Steelmaking, foundries and alloy production" },
          { k: "Supply", v: "Industrial quantities and agreed grades" },
          { k: "Documentation", v: "Analysis certificates available on request" },
        ],
        uses: ["Steelmaking", "Foundries", "Special alloy production", "Metal treatment"],
      },
      {
        slug: "carbourisers",
        name: "CARBURISERS",
        categoryEn: "Carburisers",
        spec: "6 carbon additive products",
        desc: "Carbon raisers and carburising materials for foundry and steel production.",
        long: "Our carburisers help control carbon content and support consistent melt chemistry. We offer petroleum coke, metcoke and sulphur-specific carburising materials for foundry and steelmaking requirements.",
        items: [
          "Graphitized Petroleum Coke",
          "Petroleum Coke",
          "Metcoke",
          "High & Low Sulphur Carburiser",
          "Steam Coke",
          "Anthracite",
        ],
        specs: [
          { k: "Category", v: "Carbon raisers and carburising materials" },
          { k: "Applications", v: "Foundry, induction furnace and steelmaking" },
          { k: "Options", v: "High and low sulphur grades" },
          { k: "Supply", v: "Bulk and bagged supply by agreement" },
        ],
        uses: ["Iron foundries", "Steel foundries", "Induction furnaces", "Melt chemistry control"],
      },
      {
        slug: "virgin-metals",
        name: "VIRGIN METALS",
        categoryEn: "Virgin Metals",
        spec: "5 primary metal products",
        desc: "Primary metals for alloying, melting and controlled industrial chemistry.",
        long: "Our virgin metal range provides clean primary materials for foundry additions, alloy manufacture and industrial melting operations. We can discuss the required grade, form, packing and delivery schedule for each order.",
        items: ["Silicon Metal", "Manganese Metal", "Magnesium Metal", "Moly Metal", "Zinc"],
        specs: [
          { k: "Category", v: "Primary and virgin metals" },
          { k: "Applications", v: "Alloying, melting and metal production" },
          { k: "Supply", v: "Grade, form and packing by requirement" },
          { k: "Documentation", v: "Product documentation available on request" },
        ],
        uses: ["Alloy production", "Foundry additions", "Metal refining", "Industrial melting"],
      },
      {
        slug: "minerals-ores",
        name: "MINERALS & ORES",
        categoryEn: "Minerals & Ores",
        spec: "7 mineral and ore products",
        desc: "Industrial minerals, ores and furnace feed materials for processing operations.",
        long: "We source and supply selected minerals and ores for industrial processing, refractory preparation and furnace operations. Availability, sizing and quality parameters are confirmed for each enquiry.",
        items: ["Iron Ore", "Bauxite", "Magnesium Ore", "Iron Ore Pellet", "Calcine", "Silica Sand", "Manganese Ore"],
        specs: [
          { k: "Category", v: "Minerals, ores and processed feed materials" },
          { k: "Applications", v: "Steel, foundry, refractory and industrial processing" },
          { k: "Supply", v: "Bulk, container and agreed packing options" },
          { k: "Quality", v: "Parameters confirmed against the enquiry" },
        ],
        uses: ["Steel production", "Furnace feed", "Refractory production", "Industrial processing"],
      },
      {
        slug: "refractories",
        name: "REFRACTORIES",
        categoryEn: "Refractories",
        spec: "5 refractory products",
        desc: "Ramming masses, castable cements and fire clay for furnace linings.",
        long: "Our refractory materials are selected for furnace lining, repair and heat-resistant applications. We supply acidic and basic ramming masses, castable cements and fire clay for industrial maintenance and new installations.",
        items: ["Acidic Ramming Mass", "Basic Ramming Mass", "Castable Cements", "Fire Clay", "Boric Acid"],
        specs: [
          { k: "Category", v: "Furnace and heat-resistant materials" },
          { k: "Applications", v: "Lining, repair and maintenance" },
          { k: "Products", v: "Ramming masses, castables and fire clay" },
          { k: "Supply", v: "Industrial quantities and agreed packing" },
        ],
        uses: ["Induction furnaces", "Furnace lining", "Hot repair", "Foundry maintenance"],
      },
      {
        slug: "steel-products",
        name: "STEEL PRODUCTS",
        categoryEn: "Steel Products",
        spec: "6 steel products",
        desc: "Steel products and scrap for industrial projects and steelmaking supply.",
        long: "We supply steel products and scrap for steelmakers, construction companies and industrial projects, with specifications, quantities and packing coordinated around each requirement.",
        items: ["Rebar", "Wire Rod", "Billets", "Ferrous Scrap", "Non-Ferrous Scrap", "Mid Scale"],
        specs: [
          { k: "Category", v: "Steel products and scrap" },
          { k: "Applications", v: "Construction, steelmaking and industrial projects" },
          { k: "Supply", v: "Industrial quantities and agreed specifications" },
          { k: "Packing", v: "Arranged according to product and shipment" },
        ],
        uses: ["Construction", "Steelmaking", "Industrial manufacturing", "Recycling"],
      },
      {
        slug: "cements",
        name: "CEMENTS",
        categoryEn: "Cements",
        spec: "10 cement products",
        subheading: "Types of Cement",
        subdescription: "We supply all types of cement",
        desc: "We supply all types of cement",
        long: "",
        items: [
          "Ordinary Portland Cement OPC",
          "Sulphate Resisting Portland Cement SRC",
          "Composite Portland Cement CEM II / A-M",
          "Composite Portland Cement CEM II / B-M",
          "Pozzolanic Cement CEM IV",
          "Blast Furnace Slag Cement CEM III",
          "White Cement",
          "Masonry Cement",
          "Oil Well Cement G",
          "Cement Raw Materials: Limestone, Clay, Gypsum, Silica Sand",
        ],
        specs: [
          { k: "Category", v: "Cement and cement raw materials" },
          { k: "Supply", v: "Direct supply from approved manufacturers" },
          { k: "Applications", v: "Construction, factories and industrial projects" },
          { k: "Documentation", v: "Specifications and analysis certificates on request" },
        ],
        uses: ["Construction", "Industrial projects", "Cement plants", "Contracting"],
      },
    ],
    servicesSection: {
      eyebrow: "Services",
      title: "From product selection to delivery",
      body: "We help match the right material to your process, coordinate supply and prepare the shipment for your requirements.",
    },
    services: [
      { n: "01", t: "Product matching", d: "Reviewing your requirement and matching it to the right category, grade and specification." },
      { n: "02", t: "Sourcing & importing", d: "Coordinating supply sources and freight for metal products and industrial materials." },
      { n: "03", t: "Specifications & analysis", d: "Sharing product data and analysis certificates when available and requested." },
      { n: "04", t: "Packing & preparation", d: "Arranging packing and quantities for storage, transport and use." },
      { n: "05", t: "Export coordination", d: "Coordinating documents and shipments for import and export customers." },
      { n: "06", t: "Commercial follow-up", d: "Direct responses to product enquiries, availability checks and quotations." },
    ],
    about: {
      eyebrow: "About",
      title: "A supply partner for metals and foundries",
      body: "Top Trust supplies metal products and industrial materials to steelmakers, foundries and manufacturers. We focus on clear specifications, flexible sourcing and responsive communication from the first enquiry through to shipment.",
      points: [
        "Ferro alloys and metallurgical additives",
        "Carburisers and foundry treatment materials",
        "Virgin metals, minerals, ores and refractories",
        "Import and export supply tailored to the customer",
      ],
    },
    contact: {
      eyebrow: "Contact",
      title: "Request a quote",
      body: "Send the product name, quantity and required specification, and we will come back with supply details.",
      name: "Name",
      company: "Company",
      emailLabel: "Email",
      message: "Request details",
      submit: "Send request",
      sent: "Request received — we'll be in touch shortly.",
      sending: "Sending...",
      sendError: "The request could not be sent. Please try again or contact us directly.",
      emailSetup: "Email service is not configured yet.",
      phoneLabel: "Phone",
      mailLabel: "Email",
      addressLabel: "Company",
      address: "Top Trust Metal Products",
      phone: "+20 104 444 9783",
      email: "info@toptrustco.com",
      emailSecondary: "ahmed@toptrustco.com",
    },
    footerNote: "All rights reserved",
    langToggle: "ع",
  },
};